### ISSUE TITLE
Kernel compilation

### ISSUE THREAD

**Issue by halium-on-cedric** [LinerSRT/android_device_n370b#1]
Why are you using pre-built kernel, you have https://github.com/LinerSRT/n370b_n1

**Comment by LinerSRT** [comment]
I don't use prebuild kernel. And where i use prebuild? All custom rom for
this device created by me, dont use prebuild kernels

вт, 15 окт. 2019 г., 19:54 ubports-on-cedric <notifications@github.com>:

**Comment by halium-on-cedric** [comment]
https://github.com/LinerSRT/android_device_n370b/blob/LS14.1/BoardConfig.mk#L39

**Comment by halium-on-cedric** [comment]
For now porting ubuntu touch(halium) to this phone

**Comment by LinerSRT** [comment]
In the description of email, it was kernel repository. Its for testing
tree. It works but not bugless

вт, 15 окт. 2019 г., 21:14 ubports-on-cedric <notifications@github.com>:

**Comment by halium-on-cedric** [comment]
for now trying to compile kernel. And fixing errors

**Comment by halium-on-cedric** [comment]
May be later if you want, you can create branch for that.
I will pr.

**Comment by LinerSRT** [comment]
Kernel dont have compile errors or errors in work. Check your environment before do anything
